options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # 1️⃣ Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/restaurants-v1:$SHORT_SHA'
      - '.'

  # 2️⃣ Push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/restaurants-v1:$SHORT_SHA'

  # 3️⃣ Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'restaurants-v1'
      - '--image'
      - 'gcr.io/$PROJECT_ID/restaurants-v1:$SHORT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/restaurants-v1:$SHORT_SHA'


